package com.zyl.centre.entity;

// Generated 2015-11-17 16:17:44 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ServiceordrelId generated by hbm2java
 */
@Embeddable
public class ServiceordrelId implements java.io.Serializable {

	private int orderid;
	private int serviceid;

	public ServiceordrelId() {
	}

	public ServiceordrelId(int orderid, int serviceid) {
		this.orderid = orderid;
		this.serviceid = serviceid;
	}

	@Column(name = "orderid", nullable = false)
	public int getOrderid() {
		return this.orderid;
	}

	public void setOrderid(int orderid) {
		this.orderid = orderid;
	}

	@Column(name = "serviceid", nullable = false)
	public int getServiceid() {
		return this.serviceid;
	}

	public void setServiceid(int serviceid) {
		this.serviceid = serviceid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServiceordrelId))
			return false;
		ServiceordrelId castOther = (ServiceordrelId) other;

		return (this.getOrderid() == castOther.getOrderid())
				&& (this.getServiceid() == castOther.getServiceid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrderid();
		result = 37 * result + this.getServiceid();
		return result;
	}

}
