package com.zyl.centre.entity;

// Generated 2015-11-5 8:35:54 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Serviceordrel generated by hbm2java
 */
@Entity
@Table(name = "serviceordrel", catalog = "beautycentre")
public class Serviceordrel implements java.io.Serializable {

	private ServiceordrelId id;
	private Service service;
	private Order order;
	private Date date;
	private String ext1;

	public Serviceordrel() {
	}

	public Serviceordrel(ServiceordrelId id, Service service, Order order) {
		this.id = id;
		this.service = service;
		this.order = order;
	}

	public Serviceordrel(ServiceordrelId id, Service service, Order order,
			Date date, String ext1) {
		this.id = id;
		this.service = service;
		this.order = order;
		this.date = date;
		this.ext1 = ext1;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "orderid", column = @Column(name = "orderid", nullable = false)),
			@AttributeOverride(name = "serviceid", column = @Column(name = "serviceid", nullable = false)) })
	public ServiceordrelId getId() {
		return this.id;
	}

	public void setId(ServiceordrelId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "serviceid", nullable = false, insertable = false, updatable = false)
	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "orderid", nullable = false, insertable = false, updatable = false)
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 0)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "ext1", length = 10)
	public String getExt1() {
		return this.ext1;
	}

	public void setExt1(String ext1) {
		this.ext1 = ext1;
	}

}
