package com.zyl.centre.entity;

// Generated 2015-11-17 16:17:44 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Shop generated by hbm2java
 */
@Entity
@Table(name = "shop", catalog = "beautycentre")
public class Shop implements java.io.Serializable {

	private Integer shopid;
	private Area area;
	private User user;
	private String shopname;
	private Integer shoptypeid;
	private Integer state;
	private Date createtime;
	private String shopdec;
	private String ext1;
	private String ext2;
	private String ext3;
	private String shopphone;
	private String shopaddress;
	private Integer perconsum;
	private String businesstime;
	private Integer shoplevel;
	private String discountmessage;
	private Set<Imgsrc> imgsrcs = new HashSet<Imgsrc>(0);
	private Set<Service> services = new HashSet<Service>(0);

	public Shop() {
	}

	public Shop(Area area, User user, String shopname) {
		this.area = area;
		this.user = user;
		this.shopname = shopname;
	}

	public Shop(Area area, User user, String shopname, Integer shoptypeid,
			Integer state, Date createtime, String shopdec, String ext1,
			String ext2, String ext3, String shopphone, String shopaddress,
			Integer perconsum, String businesstime, Integer shoplevel,
			String discountmessage, Set<Imgsrc> imgsrcs, Set<Service> services) {
		this.area = area;
		this.user = user;
		this.shopname = shopname;
		this.shoptypeid = shoptypeid;
		this.state = state;
		this.createtime = createtime;
		this.shopdec = shopdec;
		this.ext1 = ext1;
		this.ext2 = ext2;
		this.ext3 = ext3;
		this.shopphone = shopphone;
		this.shopaddress = shopaddress;
		this.perconsum = perconsum;
		this.businesstime = businesstime;
		this.shoplevel = shoplevel;
		this.discountmessage = discountmessage;
		this.imgsrcs = imgsrcs;
		this.services = services;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "shopid", unique = true, nullable = false)
	public Integer getShopid() {
		return this.shopid;
	}

	public void setShopid(Integer shopid) {
		this.shopid = shopid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "areaid", nullable = false)
	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "createuserid", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "shopname", nullable = false, length = 100)
	public String getShopname() {
		return this.shopname;
	}

	public void setShopname(String shopname) {
		this.shopname = shopname;
	}

	@Column(name = "shoptypeid")
	public Integer getShoptypeid() {
		return this.shoptypeid;
	}

	public void setShoptypeid(Integer shoptypeid) {
		this.shoptypeid = shoptypeid;
	}

	@Column(name = "state")
	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", length = 0)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Column(name = "shopdec", length = 65535)
	public String getShopdec() {
		return this.shopdec;
	}

	public void setShopdec(String shopdec) {
		this.shopdec = shopdec;
	}

	@Column(name = "ext1", length = 10)
	public String getExt1() {
		return this.ext1;
	}

	public void setExt1(String ext1) {
		this.ext1 = ext1;
	}

	@Column(name = "ext2", length = 20)
	public String getExt2() {
		return this.ext2;
	}

	public void setExt2(String ext2) {
		this.ext2 = ext2;
	}

	@Column(name = "ext3", length = 15)
	public String getExt3() {
		return this.ext3;
	}

	public void setExt3(String ext3) {
		this.ext3 = ext3;
	}

	@Column(name = "shopphone", length = 25)
	public String getShopphone() {
		return this.shopphone;
	}

	public void setShopphone(String shopphone) {
		this.shopphone = shopphone;
	}

	@Column(name = "shopaddress", length = 100)
	public String getShopaddress() {
		return this.shopaddress;
	}

	public void setShopaddress(String shopaddress) {
		this.shopaddress = shopaddress;
	}

	@Column(name = "perconsum")
	public Integer getPerconsum() {
		return this.perconsum;
	}

	public void setPerconsum(Integer perconsum) {
		this.perconsum = perconsum;
	}

	@Column(name = "businesstime", length = 50)
	public String getBusinesstime() {
		return this.businesstime;
	}

	public void setBusinesstime(String businesstime) {
		this.businesstime = businesstime;
	}

	@Column(name = "shoplevel")
	public Integer getShoplevel() {
		return this.shoplevel;
	}

	public void setShoplevel(Integer shoplevel) {
		this.shoplevel = shoplevel;
	}

	@Column(name = "discountmessage", length = 100)
	public String getDiscountmessage() {
		return this.discountmessage;
	}

	public void setDiscountmessage(String discountmessage) {
		this.discountmessage = discountmessage;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "shop")
	public Set<Imgsrc> getImgsrcs() {
		return this.imgsrcs;
	}

	public void setImgsrcs(Set<Imgsrc> imgsrcs) {
		this.imgsrcs = imgsrcs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "shop")
	public Set<Service> getServices() {
		return this.services;
	}

	public void setServices(Set<Service> services) {
		this.services = services;
	}

}
